// Generated by scripts/bake-ground-preview.mjs.
export const GROUND_PREVIEW_TEXTURES = [
  "/lobby/baked/soil-color-99b924aa2d61a411.webp",
  "/lobby/baked/soil-normal-dad919707ff08c06.webp",
  "/lobby/baked/meadow-color-b85c872c2b677cdd.webp",
  "/lobby/baked/meadow-normal-273c45a5df6c0c17.webp",
  "/lobby/baked/rock-face-detail-ec32c09353067cb4.webp",
  "/lobby/baked/rock-face-normal-8d29f74b01241a05.webp"
];
