// Generated by scripts/bake-ground-preview.mjs.
export const GROUND_PREVIEW_TEXTURES = [
  "/lobby/baked/soil-color-99b924aa2d61a411.webp",
  "/lobby/baked/soil-normal-dad919707ff08c06.webp",
  "/lobby/baked/meadow-color-b85c872c2b677cdd.webp",
  "/lobby/baked/meadow-normal-273c45a5df6c0c17.webp",
  "/lobby/baked/rock-face-detail-c300a5cf70d6b156.webp",
  "/lobby/baked/rock-face-normal-b2fae7d0d6c157e8.webp"
];
