import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { generateTerrainData } from '../lib/lobby/terrain-bake';
import { packTerrainData } from '../lib/lobby/terrain-data-format';

async function main() {
  const data = generateTerrainData();
  const compressed = gzipSync(packTerrainData(data), { level: 9 });
  const hash = createHash('sha256').update(compressed).digest('hex').slice(0, 16);
  const file = `terrain-${hash}.bin.gz`;
  await mkdir('public/lobby/baked', { recursive: true });
  await writeFile(`public/lobby/baked/${file}`, compressed);
  await writeFile('lib/lobby/terrain-data-manifest.ts', `// Generated by scripts/bake-terrain.ts.\nexport const TERRAIN_DATA_URL = '/lobby/baked/${file}';\n`);
  console.log(`Baked ${data.near.length + data.far.length} heights and masks: ${compressed.length} bytes`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
